# Generated by Django 3.0.5 on 2020-04-15 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('documents', models.FileField(upload_to='contestant_docs')),
            ],
            options={
                'db_table': 'contestant',
            },
        ),
        migrations.CreateModel(
            name='VacancyPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vacancy_position',
            },
        ),
        migrations.CreateModel(
            name='ContestSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='contestant.Contest')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='contestant.Contestant')),
            ],
            options={
                'db_table': 'contest_summary',
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestant.Contest')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='contestant.Contestant')),
            ],
            options={
                'db_table': 'contest_participant',
            },
        ),
        migrations.CreateModel(
            name='ContestCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestant.Contest')),
            ],
            options={
                'db_table': 'contest_commission',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='vacancy_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contestant.VacancyPosition'),
        ),
    ]
