# Generated by Django 3.0.5 on 2020-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='required_documents',
            field=models.FileField(default='contest_docs/trebuyemiye_documenti.docx', upload_to=''),
        ),
    ]
