# Generated by Django 3.0.5 on 2020-04-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0002_contest_required_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='required_documents',
            field=models.FileField(default='contest_docs/trebuyemiye_documenti.zip', upload_to=''),
        ),
    ]
