# Generated by Django 3.0.5 on 2020-04-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contestant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_document', models.FileField(upload_to='')),
                ('checked', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contestant.Employee')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestant.Contest')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestant.Contestant')),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
