# Generated by Django 3.0.5 on 2020-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
