# Generated by Django 3.0.5 on 2020-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200412_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='employee_pics/default.jpg', upload_to='employee_pics'),
        ),
    ]
